[package]
name = "ia8"
version = "0.1.0"
authors = ["Giacomo Menchi"]  #CHANGE USER TO YOU
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adafruit_io_http = "0.1.1"
rust_gpiozero = "0.2.0"