[package]
name = "ia9"
version = "0.1.0"
authors = ["Giacomo Menchi"]  #CHANGE USER TO YOU
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
run_script = "0.6.3"
