[package]
name = "rust_template"
version = "0.1.0"
authors = ["Giacomo and Silja"]  #CHANGE USER TO YOU
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pid = "2.1.0"
rust_gpiozero = "0.2.0"
rpi_embedded = "0.1.0"
